seeds:
  - Setting:
      id: 1
      name: "start_date"
      value: "2021-09-02 20:30:00"
  - Setting:
      id: 2
      name: "end_date"
      value: "2021-11-25 20:30:00"
  - Setting:
      id: 3
      name: "event_title"
      value: "Driven.t"
  - Setting:
      id: 4
      name: "background_image"
      value: "linear-gradient(to right, #FA4098, #FFD77F)"
  - Setting:
      id: 5
      name: "logo_image"
      value: "https://driveneducation.com.br/wp-content/uploads/2021/07/logo-footer.svg"
  - Modality:
      id: 1
      name: "presential"
      totalVacancy: 10
      availableVacancy: 10
      price: 25000
  - Modality:
      id: 2
      name: "online"
      totalVacancy: 20
      availableVacancy: 10
      price: 10000
  - Accommodation:
      id: 1
      name: "withoutHotel"
      price: 0
  - Accommodation:
      id: 2
      name: "withHotel"
      price: 35000
